/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EvaluateRouteImport } from './routes/evaluate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SociologyIndexRouteImport } from './routes/sociology.index'
import { Route as PrelimsIndexRouteImport } from './routes/prelims.index'
import { Route as QuestionIdRouteImport } from './routes/question.$id'
import { Route as GsPaperRouteImport } from './routes/gs.$paper'
import { Route as GsPaperIndexRouteImport } from './routes/gs.$paper.index'
import { Route as PrelimsYearYearRouteImport } from './routes/prelims.year.$year'
import { Route as PrelimsSubjectSubjectRouteImport } from './routes/prelims.subject.$subject'
import { Route as PrelimsResultAttemptIdRouteImport } from './routes/prelims.result.$attemptId'
import { Route as GsPaperSubjectRouteImport } from './routes/gs.$paper.$subject'
import { Route as AuthenticatedEvaluateUploadRouteImport } from './routes/_authenticated/evaluate.upload'
import { Route as AuthenticatedEvaluateHistoryRouteImport } from './routes/_authenticated/evaluate.history'
import { Route as AuthenticatedEvaluateIdRouteImport } from './routes/_authenticated/evaluate.$id'
import { Route as GsPaperSubjectIndexRouteImport } from './routes/gs.$paper.$subject.index'
import { Route as SociologyPaperChapterTopicRouteImport } from './routes/sociology.$paper.$chapter.$topic'
import { Route as GsPaperSubjectYearRouteImport } from './routes/gs.$paper.$subject.$year'

const EvaluateRoute = EvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SociologyIndexRoute = SociologyIndexRouteImport.update({
  id: '/sociology/',
  path: '/sociology/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrelimsIndexRoute = PrelimsIndexRouteImport.update({
  id: '/prelims/',
  path: '/prelims/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIdRoute = QuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GsPaperRoute = GsPaperRouteImport.update({
  id: '/gs/$paper',
  path: '/gs/$paper',
  getParentRoute: () => rootRouteImport,
} as any)
const GsPaperIndexRoute = GsPaperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GsPaperRoute,
} as any)
const PrelimsYearYearRoute = PrelimsYearYearRouteImport.update({
  id: '/prelims/year/$year',
  path: '/prelims/year/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const PrelimsSubjectSubjectRoute = PrelimsSubjectSubjectRouteImport.update({
  id: '/prelims/subject/$subject',
  path: '/prelims/subject/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const PrelimsResultAttemptIdRoute = PrelimsResultAttemptIdRouteImport.update({
  id: '/prelims/result/$attemptId',
  path: '/prelims/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const GsPaperSubjectRoute = GsPaperSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => GsPaperRoute,
} as any)
const AuthenticatedEvaluateUploadRoute =
  AuthenticatedEvaluateUploadRouteImport.update({
    id: '/evaluate/upload',
    path: '/evaluate/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluateHistoryRoute =
  AuthenticatedEvaluateHistoryRouteImport.update({
    id: '/evaluate/history',
    path: '/evaluate/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluateIdRoute = AuthenticatedEvaluateIdRouteImport.update({
  id: '/evaluate/$id',
  path: '/evaluate/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GsPaperSubjectIndexRoute = GsPaperSubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GsPaperSubjectRoute,
} as any)
const SociologyPaperChapterTopicRoute =
  SociologyPaperChapterTopicRouteImport.update({
    id: '/sociology/$paper/$chapter/$topic',
    path: '/sociology/$paper/$chapter/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)
const GsPaperSubjectYearRoute = GsPaperSubjectYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => GsPaperSubjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/evaluate': typeof EvaluateRoute
  '/gs/$paper': typeof GsPaperRouteWithChildren
  '/question/$id': typeof QuestionIdRoute
  '/prelims/': typeof PrelimsIndexRoute
  '/sociology/': typeof SociologyIndexRoute
  '/evaluate/$id': typeof AuthenticatedEvaluateIdRoute
  '/evaluate/history': typeof AuthenticatedEvaluateHistoryRoute
  '/evaluate/upload': typeof AuthenticatedEvaluateUploadRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectRouteWithChildren
  '/prelims/result/$attemptId': typeof PrelimsResultAttemptIdRoute
  '/prelims/subject/$subject': typeof PrelimsSubjectSubjectRoute
  '/prelims/year/$year': typeof PrelimsYearYearRoute
  '/gs/$paper/': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/sociology/$paper/$chapter/$topic': typeof SociologyPaperChapterTopicRoute
  '/gs/$paper/$subject/': typeof GsPaperSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/evaluate': typeof EvaluateRoute
  '/question/$id': typeof QuestionIdRoute
  '/prelims': typeof PrelimsIndexRoute
  '/sociology': typeof SociologyIndexRoute
  '/evaluate/$id': typeof AuthenticatedEvaluateIdRoute
  '/evaluate/history': typeof AuthenticatedEvaluateHistoryRoute
  '/evaluate/upload': typeof AuthenticatedEvaluateUploadRoute
  '/prelims/result/$attemptId': typeof PrelimsResultAttemptIdRoute
  '/prelims/subject/$subject': typeof PrelimsSubjectSubjectRoute
  '/prelims/year/$year': typeof PrelimsYearYearRoute
  '/gs/$paper': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/sociology/$paper/$chapter/$topic': typeof SociologyPaperChapterTopicRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/evaluate': typeof EvaluateRoute
  '/gs/$paper': typeof GsPaperRouteWithChildren
  '/question/$id': typeof QuestionIdRoute
  '/prelims/': typeof PrelimsIndexRoute
  '/sociology/': typeof SociologyIndexRoute
  '/_authenticated/evaluate/$id': typeof AuthenticatedEvaluateIdRoute
  '/_authenticated/evaluate/history': typeof AuthenticatedEvaluateHistoryRoute
  '/_authenticated/evaluate/upload': typeof AuthenticatedEvaluateUploadRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectRouteWithChildren
  '/prelims/result/$attemptId': typeof PrelimsResultAttemptIdRoute
  '/prelims/subject/$subject': typeof PrelimsSubjectSubjectRoute
  '/prelims/year/$year': typeof PrelimsYearYearRoute
  '/gs/$paper/': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/sociology/$paper/$chapter/$topic': typeof SociologyPaperChapterTopicRoute
  '/gs/$paper/$subject/': typeof GsPaperSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/evaluate'
    | '/gs/$paper'
    | '/question/$id'
    | '/prelims/'
    | '/sociology/'
    | '/evaluate/$id'
    | '/evaluate/history'
    | '/evaluate/upload'
    | '/gs/$paper/$subject'
    | '/prelims/result/$attemptId'
    | '/prelims/subject/$subject'
    | '/prelims/year/$year'
    | '/gs/$paper/'
    | '/gs/$paper/$subject/$year'
    | '/sociology/$paper/$chapter/$topic'
    | '/gs/$paper/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/evaluate'
    | '/question/$id'
    | '/prelims'
    | '/sociology'
    | '/evaluate/$id'
    | '/evaluate/history'
    | '/evaluate/upload'
    | '/prelims/result/$attemptId'
    | '/prelims/subject/$subject'
    | '/prelims/year/$year'
    | '/gs/$paper'
    | '/gs/$paper/$subject/$year'
    | '/sociology/$paper/$chapter/$topic'
    | '/gs/$paper/$subject'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/evaluate'
    | '/gs/$paper'
    | '/question/$id'
    | '/prelims/'
    | '/sociology/'
    | '/_authenticated/evaluate/$id'
    | '/_authenticated/evaluate/history'
    | '/_authenticated/evaluate/upload'
    | '/gs/$paper/$subject'
    | '/prelims/result/$attemptId'
    | '/prelims/subject/$subject'
    | '/prelims/year/$year'
    | '/gs/$paper/'
    | '/gs/$paper/$subject/$year'
    | '/sociology/$paper/$chapter/$topic'
    | '/gs/$paper/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EvaluateRoute: typeof EvaluateRoute
  GsPaperRoute: typeof GsPaperRouteWithChildren
  QuestionIdRoute: typeof QuestionIdRoute
  PrelimsIndexRoute: typeof PrelimsIndexRoute
  SociologyIndexRoute: typeof SociologyIndexRoute
  PrelimsResultAttemptIdRoute: typeof PrelimsResultAttemptIdRoute
  PrelimsSubjectSubjectRoute: typeof PrelimsSubjectSubjectRoute
  PrelimsYearYearRoute: typeof PrelimsYearYearRoute
  SociologyPaperChapterTopicRoute: typeof SociologyPaperChapterTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/evaluate': {
      id: '/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof EvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sociology/': {
      id: '/sociology/'
      path: '/sociology'
      fullPath: '/sociology/'
      preLoaderRoute: typeof SociologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prelims/': {
      id: '/prelims/'
      path: '/prelims'
      fullPath: '/prelims/'
      preLoaderRoute: typeof PrelimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper': {
      id: '/gs/$paper'
      path: '/gs/$paper'
      fullPath: '/gs/$paper'
      preLoaderRoute: typeof GsPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper/': {
      id: '/gs/$paper/'
      path: '/'
      fullPath: '/gs/$paper/'
      preLoaderRoute: typeof GsPaperIndexRouteImport
      parentRoute: typeof GsPaperRoute
    }
    '/prelims/year/$year': {
      id: '/prelims/year/$year'
      path: '/prelims/year/$year'
      fullPath: '/prelims/year/$year'
      preLoaderRoute: typeof PrelimsYearYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prelims/subject/$subject': {
      id: '/prelims/subject/$subject'
      path: '/prelims/subject/$subject'
      fullPath: '/prelims/subject/$subject'
      preLoaderRoute: typeof PrelimsSubjectSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prelims/result/$attemptId': {
      id: '/prelims/result/$attemptId'
      path: '/prelims/result/$attemptId'
      fullPath: '/prelims/result/$attemptId'
      preLoaderRoute: typeof PrelimsResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper/$subject': {
      id: '/gs/$paper/$subject'
      path: '/$subject'
      fullPath: '/gs/$paper/$subject'
      preLoaderRoute: typeof GsPaperSubjectRouteImport
      parentRoute: typeof GsPaperRoute
    }
    '/_authenticated/evaluate/upload': {
      id: '/_authenticated/evaluate/upload'
      path: '/evaluate/upload'
      fullPath: '/evaluate/upload'
      preLoaderRoute: typeof AuthenticatedEvaluateUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluate/history': {
      id: '/_authenticated/evaluate/history'
      path: '/evaluate/history'
      fullPath: '/evaluate/history'
      preLoaderRoute: typeof AuthenticatedEvaluateHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluate/$id': {
      id: '/_authenticated/evaluate/$id'
      path: '/evaluate/$id'
      fullPath: '/evaluate/$id'
      preLoaderRoute: typeof AuthenticatedEvaluateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/gs/$paper/$subject/': {
      id: '/gs/$paper/$subject/'
      path: '/'
      fullPath: '/gs/$paper/$subject/'
      preLoaderRoute: typeof GsPaperSubjectIndexRouteImport
      parentRoute: typeof GsPaperSubjectRoute
    }
    '/sociology/$paper/$chapter/$topic': {
      id: '/sociology/$paper/$chapter/$topic'
      path: '/sociology/$paper/$chapter/$topic'
      fullPath: '/sociology/$paper/$chapter/$topic'
      preLoaderRoute: typeof SociologyPaperChapterTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper/$subject/$year': {
      id: '/gs/$paper/$subject/$year'
      path: '/$year'
      fullPath: '/gs/$paper/$subject/$year'
      preLoaderRoute: typeof GsPaperSubjectYearRouteImport
      parentRoute: typeof GsPaperSubjectRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEvaluateIdRoute: typeof AuthenticatedEvaluateIdRoute
  AuthenticatedEvaluateHistoryRoute: typeof AuthenticatedEvaluateHistoryRoute
  AuthenticatedEvaluateUploadRoute: typeof AuthenticatedEvaluateUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEvaluateIdRoute: AuthenticatedEvaluateIdRoute,
  AuthenticatedEvaluateHistoryRoute: AuthenticatedEvaluateHistoryRoute,
  AuthenticatedEvaluateUploadRoute: AuthenticatedEvaluateUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GsPaperSubjectRouteChildren {
  GsPaperSubjectYearRoute: typeof GsPaperSubjectYearRoute
  GsPaperSubjectIndexRoute: typeof GsPaperSubjectIndexRoute
}

const GsPaperSubjectRouteChildren: GsPaperSubjectRouteChildren = {
  GsPaperSubjectYearRoute: GsPaperSubjectYearRoute,
  GsPaperSubjectIndexRoute: GsPaperSubjectIndexRoute,
}

const GsPaperSubjectRouteWithChildren = GsPaperSubjectRoute._addFileChildren(
  GsPaperSubjectRouteChildren,
)

interface GsPaperRouteChildren {
  GsPaperSubjectRoute: typeof GsPaperSubjectRouteWithChildren
  GsPaperIndexRoute: typeof GsPaperIndexRoute
}

const GsPaperRouteChildren: GsPaperRouteChildren = {
  GsPaperSubjectRoute: GsPaperSubjectRouteWithChildren,
  GsPaperIndexRoute: GsPaperIndexRoute,
}

const GsPaperRouteWithChildren =
  GsPaperRoute._addFileChildren(GsPaperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EvaluateRoute: EvaluateRoute,
  GsPaperRoute: GsPaperRouteWithChildren,
  QuestionIdRoute: QuestionIdRoute,
  PrelimsIndexRoute: PrelimsIndexRoute,
  SociologyIndexRoute: SociologyIndexRoute,
  PrelimsResultAttemptIdRoute: PrelimsResultAttemptIdRoute,
  PrelimsSubjectSubjectRoute: PrelimsSubjectSubjectRoute,
  PrelimsYearYearRoute: PrelimsYearYearRoute,
  SociologyPaperChapterTopicRoute: SociologyPaperChapterTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
