/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionIdRouteImport } from './routes/question.$id'
import { Route as GsPaperRouteImport } from './routes/gs.$paper'
import { Route as GsPaperIndexRouteImport } from './routes/gs.$paper.index'
import { Route as GsPaperSubjectRouteImport } from './routes/gs.$paper.$subject'
import { Route as GsPaperSubjectIndexRouteImport } from './routes/gs.$paper.$subject.index'
import { Route as GsPaperSubjectYearRouteImport } from './routes/gs.$paper.$subject.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIdRoute = QuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GsPaperRoute = GsPaperRouteImport.update({
  id: '/gs/$paper',
  path: '/gs/$paper',
  getParentRoute: () => rootRouteImport,
} as any)
const GsPaperIndexRoute = GsPaperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GsPaperRoute,
} as any)
const GsPaperSubjectRoute = GsPaperSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => GsPaperRoute,
} as any)
const GsPaperSubjectIndexRoute = GsPaperSubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GsPaperSubjectRoute,
} as any)
const GsPaperSubjectYearRoute = GsPaperSubjectYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => GsPaperSubjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gs/$paper': typeof GsPaperRouteWithChildren
  '/question/$id': typeof QuestionIdRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectRouteWithChildren
  '/gs/$paper/': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/gs/$paper/$subject/': typeof GsPaperSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/question/$id': typeof QuestionIdRoute
  '/gs/$paper': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gs/$paper': typeof GsPaperRouteWithChildren
  '/question/$id': typeof QuestionIdRoute
  '/gs/$paper/$subject': typeof GsPaperSubjectRouteWithChildren
  '/gs/$paper/': typeof GsPaperIndexRoute
  '/gs/$paper/$subject/$year': typeof GsPaperSubjectYearRoute
  '/gs/$paper/$subject/': typeof GsPaperSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gs/$paper'
    | '/question/$id'
    | '/gs/$paper/$subject'
    | '/gs/$paper/'
    | '/gs/$paper/$subject/$year'
    | '/gs/$paper/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/question/$id'
    | '/gs/$paper'
    | '/gs/$paper/$subject/$year'
    | '/gs/$paper/$subject'
  id:
    | '__root__'
    | '/'
    | '/gs/$paper'
    | '/question/$id'
    | '/gs/$paper/$subject'
    | '/gs/$paper/'
    | '/gs/$paper/$subject/$year'
    | '/gs/$paper/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GsPaperRoute: typeof GsPaperRouteWithChildren
  QuestionIdRoute: typeof QuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper': {
      id: '/gs/$paper'
      path: '/gs/$paper'
      fullPath: '/gs/$paper'
      preLoaderRoute: typeof GsPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gs/$paper/': {
      id: '/gs/$paper/'
      path: '/'
      fullPath: '/gs/$paper/'
      preLoaderRoute: typeof GsPaperIndexRouteImport
      parentRoute: typeof GsPaperRoute
    }
    '/gs/$paper/$subject': {
      id: '/gs/$paper/$subject'
      path: '/$subject'
      fullPath: '/gs/$paper/$subject'
      preLoaderRoute: typeof GsPaperSubjectRouteImport
      parentRoute: typeof GsPaperRoute
    }
    '/gs/$paper/$subject/': {
      id: '/gs/$paper/$subject/'
      path: '/'
      fullPath: '/gs/$paper/$subject/'
      preLoaderRoute: typeof GsPaperSubjectIndexRouteImport
      parentRoute: typeof GsPaperSubjectRoute
    }
    '/gs/$paper/$subject/$year': {
      id: '/gs/$paper/$subject/$year'
      path: '/$year'
      fullPath: '/gs/$paper/$subject/$year'
      preLoaderRoute: typeof GsPaperSubjectYearRouteImport
      parentRoute: typeof GsPaperSubjectRoute
    }
  }
}

interface GsPaperSubjectRouteChildren {
  GsPaperSubjectYearRoute: typeof GsPaperSubjectYearRoute
  GsPaperSubjectIndexRoute: typeof GsPaperSubjectIndexRoute
}

const GsPaperSubjectRouteChildren: GsPaperSubjectRouteChildren = {
  GsPaperSubjectYearRoute: GsPaperSubjectYearRoute,
  GsPaperSubjectIndexRoute: GsPaperSubjectIndexRoute,
}

const GsPaperSubjectRouteWithChildren = GsPaperSubjectRoute._addFileChildren(
  GsPaperSubjectRouteChildren,
)

interface GsPaperRouteChildren {
  GsPaperSubjectRoute: typeof GsPaperSubjectRouteWithChildren
  GsPaperIndexRoute: typeof GsPaperIndexRoute
}

const GsPaperRouteChildren: GsPaperRouteChildren = {
  GsPaperSubjectRoute: GsPaperSubjectRouteWithChildren,
  GsPaperIndexRoute: GsPaperIndexRoute,
}

const GsPaperRouteWithChildren =
  GsPaperRoute._addFileChildren(GsPaperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GsPaperRoute: GsPaperRouteWithChildren,
  QuestionIdRoute: QuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
